# experiment name
exp_name: "test"
exp_desc: "test our yaml file"

batch_size: 64

num_epochs: 100

learning_rate: 0.001

weight_decay: 0.001

warm_up_epochs: 10

num_workers: 8

model_name: 'effnetv2'